name: CI Pipeline

on:
  push:
    branches:
      [main, master]
  pull_request:
    branches:
      [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t gestion-citas .

